### ISSUE TITLE
Enable all engines

### ISSUE THREAD

**Issue by FakeShemp** [flathub/org.scummvm.ScummVM#20]
Is there a reason for the flatpak build to not include all engines?

Right now I'm getting `Escape from Monkey Island support is not compiled in` when trying to run it, but it is detected fine in the GUI.

**Comment by lotharsm** [comment]
Hey there!

For the stable releases, we at ScummVM explicitly disable the unstable engines for official releases because only the really stable ones should be in there. Currently, this evolves Escape from Monkey Island because the game still has some bugs left impacting gameplay.

Thus, from an "upstream perspective", I recommend following this procedure and build ScummVM with the `--enable-release` flag which disables the unstable engines. The behaviour of the FlatPak will then follow our official builds.

**Comment by AsciiWolf** [comment]
Hi Lothar, thanks for the comment! I see that we [already use](https://github.com/flathub/org.scummvm.ScummVM/blob/master/org.scummvm.ScummVM.json#L125) the `--enable-release` flag, so I suppose this ticket could be closed? :-)

**Comment by lotharsm** [comment]
Yes, if you want to stay as close to our guidelines as possible and basically making the FlatPak an "official" release, this ticket should be closed indeed. 🙂

**Comment by AsciiWolf** [comment]
Ok. :-) By the way, feel free to let me know if you are interested in push rights to this repo.
